import { Sometype_Mono } from "next/font/google";
import "./globals.css";
import MainNav from "@/components/MainNav";
import PageTransition from "@/components/PageTransition";
import RectangleTransition from "@/components/RectangleTransition";
import Gradient from "@/components/Gradient";
import Header from "@/components/Header";

const sometypeMono = Sometype_Mono({
  variable: "--font-sometype-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sometypeMono.variable} antialiased`}>
        
        <Gradient />

        <RectangleTransition />
        <PageTransition>
          <div className="flex">
            <div className= "hidden 2xl:flex w-[285px] h-screen bg-secondary">
              <MainNav />
            </div>
            <div className="w-full max-w-[960px] px-[15px] mx-auto overflow-x-hidden">
              <Header />
              <div className="w-full pt-0 2xl:pt-0">{children}</div>
            </div>
        </div>
        </PageTransition>
        
      </body>
    </html>
  );
}
